# Generated by simple compiler -> Python
import sys

# Runtime helpers
def __input__():
    return input()

def main():
    print((10 + 2))
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main())